### ISSUE TITLE
Adding links to the presentation and recording used on developer days NY 2023

### ISSUE THREAD

**Issue by jillesca** [NSO-developer/nso-service-dev-practices#4]
It will be nice if you can add a link to your presentation on https://community.cisco.com/t5/nso-developer-hub-knowledge-articles/2023-devdays-us-good-software-practices-in-nso-development/ta-p/4983108/jump-to/first-unread-message 

And the youtube recording https://www.youtube.com/watch?v=i2Cf7gPOcsQ

**Comment by bdolenc** [comment]
Done in #5 .
